include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:

analyzer:
  exclude:
    - "lib/**/*.freezed.dart"
    - "lib/**/*.g.dart"

  errors:
    always_put_control_body_on_new_line: ignore
