name: tpl_flutter
description: A fluter project template with MVVM.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.5.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.1.1
  http: ^0.13.5
  json_serializable: ^6.5.4
  pedantic_mono: ^1.20.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  uses-material-design: true
